-- Create names table for culturally appropriate persona names by country
CREATE TABLE names (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    country VARCHAR(2) NOT NULL,
    CONSTRAINT uk_name_gender_country UNIQUE(name, gender, country)
);

CREATE INDEX idx_names_country_gender ON names(country, gender);

-- RU - RUSSIA (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Alexei', 'male', 'RU'),
('Andrey', 'male', 'RU'),
('Dmitry', 'male', 'RU'),
('Evgeny', 'male', 'RU'),
('Igor', 'male', 'RU'),
('Ivan', 'male', 'RU'),
('Kirill', 'male', 'RU'),
('Mikhail', 'male', 'RU'),
('Sergey', 'male', 'RU'),
('Vladimir', 'male', 'RU'),
('Alexandra', 'female', 'RU'),
('Anastasia', 'female', 'RU'),
('Anna', 'female', 'RU'),
('Ekaterina', 'female', 'RU'),
('Elena', 'female', 'RU'),
('Irina', 'female', 'RU'),
('Marina', 'female', 'RU'),
('Natalia', 'female', 'RU'),
('Olga', 'female', 'RU'),
('Tatiana', 'female', 'RU');

-- US - UNITED STATES (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('James', 'male', 'US'),
('Michael', 'male', 'US'),
('David', 'male', 'US'),
('Robert', 'male', 'US'),
('John', 'male', 'US'),
('William', 'male', 'US'),
('Richard', 'male', 'US'),
('Joseph', 'male', 'US'),
('Thomas', 'male', 'US'),
('Charles', 'male', 'US'),
('Mary', 'female', 'US'),
('Patricia', 'female', 'US'),
('Jennifer', 'female', 'US'),
('Linda', 'female', 'US'),
('Barbara', 'female', 'US'),
('Elizabeth', 'female', 'US'),
('Susan', 'female', 'US'),
('Jessica', 'female', 'US'),
('Sarah', 'female', 'US'),
('Karen', 'female', 'US');

-- GB - UNITED KINGDOM (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('James', 'male', 'GB'),
('David', 'male', 'GB'),
('Michael', 'male', 'GB'),
('Andrew', 'male', 'GB'),
('Christopher', 'male', 'GB'),
('Simon', 'male', 'GB'),
('Paul', 'male', 'GB'),
('Mark', 'male', 'GB'),
('Robert', 'male', 'GB'),
('John', 'male', 'GB'),
('Mary', 'female', 'GB'),
('Patricia', 'female', 'GB'),
('Susan', 'female', 'GB'),
('Jennifer', 'female', 'GB'),
('Linda', 'female', 'GB'),
('Barbara', 'female', 'GB'),
('Elizabeth', 'female', 'GB'),
('Claire', 'female', 'GB'),
('Sophie', 'female', 'GB'),
('Laura', 'female', 'GB');

-- DE - GERMANY (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Michael', 'male', 'DE'),
('Thomas', 'male', 'DE'),
('Andreas', 'male', 'DE'),
('Klaus', 'male', 'DE'),
('Jürgen', 'male', 'DE'),
('Hans', 'male', 'DE'),
('Dieter', 'male', 'DE'),
('Peter', 'male', 'DE'),
('Frank', 'male', 'DE'),
('Stefan', 'male', 'DE'),
('Heidi', 'female', 'DE'),
('Monika', 'female', 'DE'),
('Petra', 'female', 'DE'),
('Helga', 'female', 'DE'),
('Gabriele', 'female', 'DE'),
('Andrea', 'female', 'DE'),
('Claudia', 'female', 'DE'),
('Ursula', 'female', 'DE'),
('Renate', 'female', 'DE'),
('Ingrid', 'female', 'DE');

-- FR - FRANCE (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Jean', 'male', 'FR'),
('Michel', 'male', 'FR'),
('André', 'male', 'FR'),
('Philippe', 'male', 'FR'),
('Marc', 'male', 'FR'),
('Jacques', 'male', 'FR'),
('Bernard', 'male', 'FR'),
('Pierre', 'male', 'FR'),
('Claude', 'male', 'FR'),
('François', 'male', 'FR'),
('Marie', 'female', 'FR'),
('Francoise', 'female', 'FR'),
('Monique', 'female', 'FR'),
('Nicole', 'female', 'FR'),
('Jeanne', 'female', 'FR'),
('Christiane', 'female', 'FR'),
('Anne', 'female', 'FR'),
('Sylvie', 'female', 'FR'),
('Catherine', 'female', 'FR'),
('Danielle', 'female', 'FR');

-- IT - ITALY (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Giuseppe', 'male', 'IT'),
('Antonio', 'male', 'IT'),
('Giovanni', 'male', 'IT'),
('Marco', 'male', 'IT'),
('Angelo', 'male', 'IT'),
('Luigi', 'male', 'IT'),
('Salvatore', 'male', 'IT'),
('Paolo', 'male', 'IT'),
('Francesco', 'male', 'IT'),
('Carlo', 'male', 'IT'),
('Maria', 'female', 'IT'),
('Rosa', 'female', 'IT'),
('Anna', 'female', 'IT'),
('Antonia', 'female', 'IT'),
('Lucia', 'female', 'IT'),
('Francesca', 'female', 'IT'),
('Angela', 'female', 'IT'),
('Caterina', 'female', 'IT'),
('Giovanna', 'female', 'IT'),
('Carmela', 'female', 'IT');

-- ES - SPAIN (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Jose', 'male', 'ES'),
('Manuel', 'male', 'ES'),
('Juan', 'male', 'ES'),
('Francisco', 'male', 'ES'),
('Antonio', 'male', 'ES'),
('Miguel', 'male', 'ES'),
('Fernando', 'male', 'ES'),
('Javier', 'male', 'ES'),
('Pedro', 'male', 'ES'),
('Carlos', 'male', 'ES'),
('Maria', 'female', 'ES'),
('Carmen', 'female', 'ES'),
('Isabel', 'female', 'ES'),
('Rosa', 'female', 'ES'),
('Francisca', 'female', 'ES'),
('Antonia', 'female', 'ES'),
('Dolores', 'female', 'ES'),
('Pilar', 'female', 'ES'),
('Angela', 'female', 'ES'),
('Encarnacion', 'female', 'ES');

-- BR - BRAZIL (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Jose', 'male', 'BR'),
('Luis', 'male', 'BR'),
('Carlos', 'male', 'BR'),
('Antonio', 'male', 'BR'),
('Francisco', 'male', 'BR'),
('Joao', 'male', 'BR'),
('Paulo', 'male', 'BR'),
('Pedro', 'male', 'BR'),
('Marcos', 'male', 'BR'),
('David', 'male', 'BR'),
('Maria', 'female', 'BR'),
('Rosa', 'female', 'BR'),
('Francisca', 'female', 'BR'),
('Antonia', 'female', 'BR'),
('Joana', 'female', 'BR'),
('Paula', 'female', 'BR'),
('Carla', 'female', 'BR'),
('Beatriz', 'female', 'BR'),
('Sandra', 'female', 'BR'),
('Patricia', 'female', 'BR');

-- CN - CHINA (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Wei', 'male', 'CN'),
('Wang', 'male', 'CN'),
('Feng', 'male', 'CN'),
('Ming', 'male', 'CN'),
('Lei', 'male', 'CN'),
('Gang', 'male', 'CN'),
('Chen', 'male', 'CN'),
('Tao', 'male', 'CN'),
('Jun', 'male', 'CN'),
('Yang', 'male', 'CN'),
('Fang', 'female', 'CN'),
('Mei', 'female', 'CN'),
('Li', 'female', 'CN'),
('Qing', 'female', 'CN'),
('Hui', 'female', 'CN'),
('Yan', 'female', 'CN'),
('Ying', 'female', 'CN'),
('Jing', 'female', 'CN'),
('Xue', 'female', 'CN'),
('Na', 'female', 'CN');

-- IN - INDIA (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Rajesh', 'male', 'IN'),
('Anil', 'male', 'IN'),
('Vijay', 'male', 'IN'),
('Suresh', 'male', 'IN'),
('Manoj', 'male', 'IN'),
('Amit', 'male', 'IN'),
('Ashok', 'male', 'IN'),
('Pradeep', 'male', 'IN'),
('Deepak', 'male', 'IN'),
('Naveen', 'male', 'IN'),
('Priya', 'female', 'IN'),
('Neha', 'female', 'IN'),
('Anjali', 'female', 'IN'),
('Pooja', 'female', 'IN'),
('Kavya', 'female', 'IN'),
('Sneha', 'female', 'IN'),
('Divya', 'female', 'IN'),
('Aruna', 'female', 'IN'),
('Lakshmi', 'female', 'IN'),
('Aisha', 'female', 'IN');

-- JP - JAPAN (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Takeshi', 'male', 'JP'),
('Kenji', 'male', 'JP'),
('Haruto', 'male', 'JP'),
('Yuki', 'male', 'JP'),
('Hiroshi', 'male', 'JP'),
('Toshio', 'male', 'JP'),
('Tetsuya', 'male', 'JP'),
('Masaru', 'male', 'JP'),
('Noboru', 'male', 'JP'),
('Shinji', 'male', 'JP'),
('Yuki', 'female', 'JP'),
('Sakura', 'female', 'JP'),
('Akira', 'female', 'JP'),
('Yumiko', 'female', 'JP'),
('Emi', 'female', 'JP'),
('Kaori', 'female', 'JP'),
('Tomoe', 'female', 'JP'),
('Aiko', 'female', 'JP'),
('Hiroko', 'female', 'JP'),
('Masako', 'female', 'JP');

-- KR - SOUTH KOREA (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Min-ho', 'male', 'KR'),
('Ji-won', 'male', 'KR'),
('Sung-ho', 'male', 'KR'),
('Tae-oh', 'male', 'KR'),
('Hyun-woo', 'male', 'KR'),
('Jae-sung', 'male', 'KR'),
('Jun-seo', 'male', 'KR'),
('Dong-hyun', 'male', 'KR'),
('Yoon-ho', 'male', 'KR'),
('Chang-min', 'male', 'KR'),
('Min-ji', 'female', 'KR'),
('Ji-woo', 'female', 'KR'),
('Sung-hee', 'female', 'KR'),
('Eun-young', 'female', 'KR'),
('Hae-won', 'female', 'KR'),
('So-young', 'female', 'KR'),
('Mi-rae', 'female', 'KR'),
('Hee-jin', 'female', 'KR'),
('Se-yeon', 'female', 'KR'),
('Jae-young', 'female', 'KR');

-- MX - MEXICO (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Jose', 'male', 'MX'),
('Juan', 'male', 'MX'),
('Carlos', 'male', 'MX'),
('Miguel', 'male', 'MX'),
('Luis', 'male', 'MX'),
('Francisco', 'male', 'MX'),
('Roberto', 'male', 'MX'),
('Antonio', 'male', 'MX'),
('Manuel', 'male', 'MX'),
('Javier', 'male', 'MX'),
('Maria', 'female', 'MX'),
('Rosa', 'female', 'MX'),
('Carmen', 'female', 'MX'),
('Guadalupe', 'female', 'MX'),
('Francisca', 'female', 'MX'),
('Alicia', 'female', 'MX'),
('Irene', 'female', 'MX'),
('Dolores', 'female', 'MX'),
('Lucia', 'female', 'MX'),
('Juana', 'female', 'MX');

-- CA - CANADA (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Michael', 'male', 'CA'),
('David', 'male', 'CA'),
('James', 'male', 'CA'),
('Robert', 'male', 'CA'),
('John', 'male', 'CA'),
('William', 'male', 'CA'),
('Richard', 'male', 'CA'),
('Joseph', 'male', 'CA'),
('Thomas', 'male', 'CA'),
('Mark', 'male', 'CA'),
('Mary', 'female', 'CA'),
('Patricia', 'female', 'CA'),
('Jennifer', 'female', 'CA'),
('Linda', 'female', 'CA'),
('Barbara', 'female', 'CA'),
('Elizabeth', 'female', 'CA'),
('Susan', 'female', 'CA'),
('Jessica', 'female', 'CA'),
('Sarah', 'female', 'CA'),
('Karen', 'female', 'CA');

-- AU - AUSTRALIA (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Michael', 'male', 'AU'),
('David', 'male', 'AU'),
('James', 'male', 'AU'),
('Robert', 'male', 'AU'),
('Andrew', 'male', 'AU'),
('John', 'male', 'AU'),
('William', 'male', 'AU'),
('Richard', 'male', 'AU'),
('Steven', 'male', 'AU'),
('Peter', 'male', 'AU'),
('Mary', 'female', 'AU'),
('Patricia', 'female', 'AU'),
('Jennifer', 'female', 'AU'),
('Linda', 'female', 'AU'),
('Barbara', 'female', 'AU'),
('Susan', 'female', 'AU'),
('Jessica', 'female', 'AU'),
('Sarah', 'female', 'AU'),
('Karen', 'female', 'AU'),
('Lisa', 'female', 'AU');

-- NL - NETHERLANDS (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Peter', 'male', 'NL'),
('Pieter', 'male', 'NL'),
('Jan', 'male', 'NL'),
('Kees', 'male', 'NL'),
('Johan', 'male', 'NL'),
('Ton', 'male', 'NL'),
('Hans', 'male', 'NL'),
('Piet', 'male', 'NL'),
('Dirk', 'male', 'NL'),
('Henk', 'male', 'NL'),
('Maria', 'female', 'NL'),
('Maria', 'female', 'NL'),
('Petra', 'female', 'NL'),
('Els', 'female', 'NL'),
('Katrien', 'female', 'NL'),
('Sofie', 'female', 'NL'),
('Anja', 'female', 'NL'),
('Lieke', 'female', 'NL'),
('Daphne', 'female', 'NL'),
('Mirjam', 'female', 'NL');

-- SE - SWEDEN (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Lars', 'male', 'SE'),
('Anders', 'male', 'SE'),
('Carl', 'male', 'SE'),
('Erik', 'male', 'SE'),
('Anders', 'male', 'SE'),
('Per', 'male', 'SE'),
('Nils', 'male', 'SE'),
('Soren', 'male', 'SE'),
('Magnus', 'male', 'SE'),
('Bengt', 'male', 'SE'),
('Ingrid', 'female', 'SE'),
('Ulla', 'female', 'SE'),
('Anna', 'female', 'SE'),
('Britta', 'female', 'SE'),
('Christina', 'female', 'SE'),
('Britt', 'female', 'SE'),
('Karin', 'female', 'SE'),
('Greta', 'female', 'SE'),
('Solveig', 'female', 'SE'),
('Astrid', 'female', 'SE');

-- PL - POLAND (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Andrzej', 'male', 'PL'),
('Tadeusz', 'male', 'PL'),
('Stanislaus', 'male', 'PL'),
('Jerzy', 'male', 'PL'),
('Ryszard', 'male', 'PL'),
('Zbigniew', 'male', 'PL'),
('Wladimir', 'male', 'PL'),
('Miroslaw', 'male', 'PL'),
('Lech', 'male', 'PL'),
('Piotr', 'male', 'PL'),
('Maria', 'female', 'PL'),
('Zofia', 'female', 'PL'),
('Helena', 'female', 'PL'),
('Danuta', 'female', 'PL'),
('Teresa', 'female', 'PL'),
('Krystyna', 'female', 'PL'),
('Stanisława', 'female', 'PL'),
('Ewa', 'female', 'PL'),
('Beata', 'female', 'PL'),
('Grażyna', 'female', 'PL');

-- TR - TURKEY (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Ali', 'male', 'TR'),
('Ahmet', 'male', 'TR'),
('Mehmet', 'male', 'TR'),
('Ibrahim', 'male', 'TR'),
('Hasan', 'male', 'TR'),
('Ismail', 'male', 'TR'),
('Mustafa', 'male', 'TR'),
('Emre', 'male', 'TR'),
('Kemal', 'male', 'TR'),
('Selim', 'male', 'TR'),
('Fatma', 'female', 'TR'),
('Ayse', 'female', 'TR'),
('Zeynep', 'female', 'TR'),
('Emine', 'female', 'TR'),
('Gulsen', 'female', 'TR'),
('Nermin', 'female', 'TR'),
('Sennur', 'female', 'TR'),
('Ceren', 'female', 'TR'),
('Derya', 'female', 'TR'),
('Nuray', 'female', 'TR');

-- NG - NIGERIA (10 male + 10 female)
INSERT INTO names (name, gender, country) VALUES
('Chinyere', 'male', 'NG'),
('Nnamdi', 'male', 'NG'),
('Chibueze', 'male', 'NG'),
('Okechukwu', 'male', 'NG'),
('Eze', 'male', 'NG'),
('Taiwo', 'male', 'NG'),
('Babatunde', 'male', 'NG'),
('Tunde', 'male', 'NG'),
('Seun', 'male', 'NG'),
('Kunle', 'male', 'NG'),
('Chioma', 'female', 'NG'),
('Zainab', 'female', 'NG'),
('Amara', 'female', 'NG'),
('Folake', 'female', 'NG'),
('Nia', 'female', 'NG'),
('Ayo', 'female', 'NG'),
('Zara', 'female', 'NG'),
('Tayo', 'female', 'NG'),
('Adanna', 'female', 'NG'),
('Blessing', 'female', 'NG');
